apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: default-builder
spec:
  serviceAccountRef:
    name: default
    namespace: default
  tag: captnfresh/kpack-test-builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/nodejs
  - group:
    - id: paketo-buildpacks/python
